# Generated by Django 4.0.5 on 2022-07-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordhistory',
            options={'verbose_name': 'Record History', 'verbose_name_plural': 'Record Histories'},
        ),
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(max_length=500, upload_to='voices/', verbose_name='Record file'),
        ),
    ]
